kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: frontend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: frontend
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        project: expense
    spec:
      volumes:
      - name: nginx
        configMap:
          name: nginx
          items:
            - key: nginx.conf
              path: nginx.conf  
      containers:
      - name: frontend
        image: sudhanaga1002/frontend:1.2.0
        resources:
          requests:
            # soft limit
            memory: "68Mi"
            cpu: "100m"
          limits:
            # hard limit
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true